# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [6]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

a = np.arange(11)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
a[3:7] = a[3:7] * -1

print(a)

[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [8]:
A = np.random.rand(3, 6)


'''
Your Code
'''

[[0.14933156 0.38191581 0.24129195 0.42608622 0.61830527 0.20630475]
 [0.44279011 0.17056374 0.48698922 0.63236956 0.10841242 0.00792768]
 [0.10358237 0.33681034 0.55904075 0.22819079 0.73942028 0.25065122]]


'\nYour Code\n'

In [14]:
answer = (A > 0.5).sum()
print(answer)

4
